server:
  port: 8765

spring:
  application:
    name: spring-cloud-gateway-server
  redis:
    host: 10.100.50.253
    password: admin
    port: 6379
  session:
    cookie-name: GATEWAY-SESSION
    store-type: redis
  cloud:
    config:
      enabled: false
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: consumer-coolkid
          uri: lb://consumer-coolkid
          predicates:
            - Path=/api/**
          filters:
            - RewritePath=/api/(?<segment>.*), /consumer-coolkid/$\{segment}
            - "RewriteResponseHeader=Set-Cookie, Path=/consumer-coolkid, Path=/api"
            - SaveSession

logging:
  level:
    root: INFO

app:
  config:
    eureka:
      port: 8761

eureka:
  instance:
    prefer-ip-address: true
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${app.config.eureka.port}/eureka/
