server:
  port: 8763
  servlet:
    context-path: /consumer-coolkid

spring:
  application:
    name: consumer-coolkid
  cloud:
    config:
      enabled: false

app:
  config:
    eureka:
      port: 8761

eureka:
  instance:
    prefer-ip-address: true
    hostname: localhost

  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${app.config.eureka.port}/eureka/

provider-coolkid:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule