server:
  port: 8763
  servlet:
    context-path: /consumer-coolkid

spring:
  application:
    name: consumer-coolkid
  cloud:
    config:
      enabled: false
  redis:
    host: 10.100.50.253
    password: admin
    port: 6379
  session:
    store-type: redis

feign:
  circuitbreaker:
    enabled: true
    group:
      enabled: true

hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: SEMAPHORE

app:
  config:
    eureka:
      port: 8761

eureka:
  instance:
    prefer-ip-address: true
    hostname: localhost

  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${app.config.eureka.port}/eureka/

provider-coolkid:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule