server:
  port: 8765

spring:
  cloud:
    config:
      enabled: false
zuul:
  routes:
    consumer-coolkid:
      path: localhost:8763/consumer-coolkid


logging:
  level:
    root: INFO

app:
  config:
    eureka:
      port: 8761

eureka:
  instance:
    prefer-ip-address: true
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${app.config.eureka.port}/eureka/
