server:
  port: 8764
  servlet:
    context-path: /provider-coolkid

spring:
  application:
    name: provider-coolkid
  cloud:
    config:
      enabled: false
  redis:
    host: 10.100.50.253
    password: admin
    port: 6379
  session:
    store-type: redis

logging:
  level:
    root: INFO

app:
  config:
    eureka:
      port: 8761

eureka:
  instance:
    prefer-ip-address: true
    hostname: localhost

  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${app.config.eureka.port}/eureka/
